import {z} from 'zod';

const BorangSchema = z.object({
    jabatan_pemohon:z.string(),
    nama_pemohon:z.string(),
    telefon_pemohon:z.string(),
    emel_pemohon:z.string(),

    jabatan_pegawai:z.string(),
    nama_pegawai:z.string(),
    telefon_pegawai:z.string(),
    emel_pegawai:z.string(),


    nama_program:z.string(),
    jumlah_peserta:z.string(),
    tarikh_mula:z.string(),
    tarikh_akhir:z.string(),
    masa_seminar:z.string(),

    tarikh_masuk:z.string(),
    tarikh_keluar:z.string(),
    bilik_seorang_L:z.string(),
    bilik_seorang_P:z.string(),
    bilik_berdua_L:z.string(),
    bilik_berdua_P:z.string(),
    catatan_ruai_inap:z.string(),

    bilik_kuliah:z.string(),
    bilik_bengkel:z.string(),
    bilik_seminar:z.string(),
    makmal_komputer:z.string(),
    dewan_rempah_ratus:z.string(),
    lain_jenis_bilik:z.string(),
    classroom:z.string(),
    cluster:z.string(),
    ushape:z.string(),
    fishbone:z.string(),
    theatre:z.string(),
    lain_susun_atur:z.string(),
    catatan_bilik_latihan:z.string(),
    lcd_projector:z.string(),
    pa:z.string(),
    portable_pa:z.string(),
    bateri:z.string(),
    flip_chart:z.string(),
    a4_paper:z.string(),
    kertas_mahjong:z.string(),
    alat_tulis:z.string(),
    lain_jenis_peralatan:z.string(),

    kod_material:z.string(),
    gl_kod:z.string(),
    pusat_kos:z.string(),
    bajet_makan_minum:z.string(),
    catatan_kos_fb:z.string(),

    tarikh_1:z.string(),
    sarapan_1:z.string(),
    minum_pagi_1:z.string(),
    makan_thari_1:z.string(),
    minum_petang_1:z.string(),
    makan_malam_1:z.string(),
    minum_malam_1:z.string(),
    
    tarikh_2:z.string(),
    sarapan_2:z.string(),
    minum_pagi_2:z.string(),
    makan_thari_2:z.string(),
    minum_petang_2:z.string(),
    makan_malam_2:z.string(),
    minum_malam_2:z.string(),

    tarikh_3:z.string(),
    sarapan_3:z.string(),
    minum_pagi_3:z.string(),
    makan_thari_3:z.string(),
    minum_petang_3:z.string(),
    makan_malam_3:z.string(),
    minum_malam_3:z.string(),

    tarikh_4:z.string(),
    sarapan_4:z.string(),
    minum_pagi_4:z.string(),
    makan_thari_4:z.string(),
    minum_petang_4:z.string(),
    makan_malam_4:z.string(),
    minum_malam_4:z.string(),

    tarikh_5:z.string(),
    sarapan_5:z.string(),
    minum_pagi_5:z.string(),
    makan_thari_5:z.string(),
    minum_petang_5:z.string(),
    makan_malam_5:z.string(),
    minum_malam_5:z.string(),
    
    tarikh_6:z.string(),
    sarapan_6:z.string(),
    minum_pagi_6:z.string(),
    makan_thari_6:z.string(),
    minum_petang_6:z.string(),
    makan_malam_6:z.string(),
    minum_malam_6:z.string(),
    
    tarikh_7:z.string(),
    sarapan_7:z.string(),
    minum_pagi_7:z.string(),
    makan_thari_7:z.string(),
    minum_petang_7:z.string(),
    makan_malam_7:z.string(),
    minum_malam_7:z.string(),

    dome_set:z.string(),
    vegetarian:z.string(),
    catatan_makan_minum:z.string(),
})

export {BorangSchema};